### ISSUE TITLE
Jack?

### ISSUE THREAD

**Issue by worikgh** [wvengen/lpx-controller#1]
Having followed your installation instructions...
```
mididings$ python3 setup.py install --user
couldn't find package 'jack'
```
Which version to jack to install?
`sudo apt install jackd2`?

**Comment by wvengen** [comment]
Hi, sorry, I've only seen your issue just now. What about:
```sh
sudo apt install libjack-jackd2-dev
```

**Comment by wvengen** [comment]
Since the move to Rust, you can download a binary instead of having to compile mididings. And jack is not even an option there (and which isn't necessary as the Launchpad X is always exposed via ALSA).
